import type { UniversalAgentConfig } from '../universalSchema'

export function exportLangGraphPython(config: UniversalAgentConfig): string {
  const modelMap: Record<string, string> = {
    'claude-opus-4-6': 'claude-opus-4-6',
    'claude-sonnet-4-6': 'claude-sonnet-4-6',
    'claude-haiku-4-5-20251001': 'claude-haiku-4-5-20251001',
    'gpt-4o': 'gpt-4o',
    'gpt-4o-mini': 'gpt-4o-mini',
    'gemini-2.0-flash': 'gemini-2.0-flash',
    'gemini-2.0-pro': 'gemini-2.0-pro',
    'gemini-2.0-ultra': 'gemini-2.0-ultra'
  }

  const langGraphModel = modelMap[config.model] ?? config.model

  const providerImport = config.provider === 'openai'
    ? 'from langchain_openai import ChatOpenAI'
    : config.provider === 'google'
      ? 'from langchain_google_genai import ChatGoogleGenerativeAI'
      : 'from langchain_anthropic import ChatAnthropic'

  const providerInit = config.provider === 'openai'
    ? `ChatOpenAI(model="${langGraphModel}")`
    : config.provider === 'google'
      ? `ChatGoogleGenerativeAI(model="${langGraphModel}")`
      : `ChatAnthropic(model="${langGraphModel}")`

  const escapedInstructions = config.instructions
    .map((line) => `    ${line}`)
    .join('\n')

  const toolDefs = config.tools
    .filter((t) => t.type !== 'agent_toolset_20260401')
    .map((t) => {
      const toolName = t.name ?? t.serverName ?? t.type
      return `    # TODO: Implement ${toolName} tool`
    })
    .join('\n')

  const dataSourceDefs = config.dataSources
    .map((ds) => `    # Data source: ${ds.name} (${ds.type}${ds.url ? `, ${ds.url}` : ''})`)
    .join('\n')

  return `"""
${config.name}

${config.description}

Generated by Forge - LangGraph export
"""

from typing import TypedDict, Annotated
from langgraph.graph import StateGraph, END
from langgraph.prebuilt import ToolNode
${providerImport}


# --- State ---
class AgentState(TypedDict):
    messages: list
    context: dict


# --- Model ---
llm = ${providerInit}

SYSTEM_PROMPT = """
${escapedInstructions}
"""


# --- Tools ---
${toolDefs || '    # No additional tools configured'}

${dataSourceDefs ? `# --- Data Sources ---\n${dataSourceDefs}\n` : ''}

# --- Nodes ---
def agent_node(state: AgentState) -> AgentState:
    """Main agent reasoning node."""
    messages = state["messages"]
    response = llm.invoke([
        {"role": "system", "content": SYSTEM_PROMPT},
        *messages
    ])
    return {"messages": messages + [response], "context": state.get("context", {})}


def should_continue(state: AgentState) -> str:
    """Determine if the agent should continue or end."""
    last_message = state["messages"][-1]
    if hasattr(last_message, "tool_calls") and last_message.tool_calls:
        return "tools"
    return "end"


# --- Graph ---
workflow = StateGraph(AgentState)
workflow.add_node("agent", agent_node)
workflow.set_entry_point("agent")
workflow.add_conditional_edges("agent", should_continue, {"tools": "agent", "end": END})

graph = workflow.compile()


if __name__ == "__main__":
    result = graph.invoke({
        "messages": [{"role": "user", "content": "Hello, what can you help me with?"}],
        "context": {}
    })
    print(result["messages"][-1].content)
`
}
