import { Trophy } from '@phosphor-icons/react'
import type { Verdict } from './judgeCard'

interface BattleOgCardProps {
  verdict: Verdict
  /** Scale factor — 1 is full 2048x1080, 0.25 for preview (512x270) */
  scale?: number
}

/**
 * Preview of the share card OG image (2048x1080 at scale=1).
 * Used in the UI to show what will be generated by the OG route.
 */
export function BattleOgCard({ verdict, scale = 0.25 }: BattleOgCardProps) {
  const width = 2048 * scale
  const height = 1080 * scale

  return (
    <div
      className="relative overflow-hidden rounded border border-bone-200 bg-bone-50 bg-paper-grain shadow-ember-lg"
      style={{ width, height }}
    >
      <div
        className="absolute inset-0 p-8"
        style={{ transform: `scale(${scale})`, transformOrigin: 'top left', width: 2048, height: 1080 }}
      >
        <div className="flex h-full flex-col p-20">
          <header className="flex items-center gap-4">
            <Trophy size={72} weight="duotone" className="text-gold-500" />
            <h1 className="font-display text-[96px] leading-none tracking-tight text-ink-900">
              Agent Battle
            </h1>
          </header>

          <div className="mt-12 grid flex-1 grid-cols-2 gap-16">
            <div className="rounded-xl border-4 border-ember-500 bg-bone-50 p-10">
              <div className="text-[28px] uppercase tracking-wider text-ink-500">Agent A</div>
              <div className="mt-4 font-display text-[72px] leading-tight text-ink-900">
                {verdict.agentAName}
              </div>
              <div className="mt-10 font-mono text-[120px] text-ember-500">
                {verdict.scoreA.toFixed(1)}
              </div>
            </div>

            <div className="rounded-xl border-4 border-iron-600 bg-bone-50 p-10">
              <div className="text-[28px] uppercase tracking-wider text-ink-500">Agent B</div>
              <div className="mt-4 font-display text-[72px] leading-tight text-ink-900">
                {verdict.agentBName}
              </div>
              <div className="mt-10 font-mono text-[120px] text-iron-600">
                {verdict.scoreB.toFixed(1)}
              </div>
            </div>
          </div>

          <footer className="mt-10 flex items-center justify-between text-[32px] text-ink-500">
            <span className="font-mono">forge.agents.sh</span>
            <span>Made with Forge</span>
          </footer>
        </div>
      </div>
    </div>
  )
}
