import type { TaskType } from '../classifier'
import type { ForgeIntent } from '../types'
import type { SeedMatch } from '../retriever'
import type { McpEntry } from '../mcpCatalog'
import type { UniversalAgentConfig } from '../config/universalSchema'
import type {
  LLMProvider,
  QualityTier,
  GenerateProviderResult,
  LintProviderResult
} from './types'

const KEYWORD_TASK_MAP: Array<{ keywords: string[]; taskType: TaskType }> = [
  { keywords: ['research', 'search', 'find', 'investigate'], taskType: 'research' },
  { keywords: ['triage', 'prioritize', 'categorize', 'route'], taskType: 'triage' },
  { keywords: ['monitor', 'watch', 'track', 'scan'], taskType: 'monitor' },
  { keywords: ['extract', 'parse', 'structured', 'pull'], taskType: 'extract' },
  { keywords: ['notify', 'send', 'alert', 'message'], taskType: 'notify' },
  { keywords: ['analyze', 'report', 'metrics', 'dashboard'], taskType: 'analyze' }
]

function slugify(name: string): string {
  return name
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-|-$/g, '')
    .slice(0, 128)
}

export class GoogleProvider implements LLMProvider {
  readonly type = 'google' as const

  getModelForTier(tier: QualityTier): string {
    switch (tier) {
      case 'fast':
        return 'gemini-2.0-flash'
      case 'balanced':
        return 'gemini-2.0-pro'
      case 'quality':
        return 'gemini-2.0-ultra'
    }
  }

  getDisplayName(): string {
    return 'Google'
  }

  async classify(prompt: string): Promise<TaskType> {
    const promptLower = prompt.toLowerCase()

    for (const { keywords, taskType } of KEYWORD_TASK_MAP) {
      for (const keyword of keywords) {
        if (promptLower.includes(keyword)) {
          return taskType
        }
      }
    }

    return 'research'
  }

  async generate(
    intent: ForgeIntent,
    seeds: SeedMatch[],
    mcps: McpEntry[]
  ): Promise<GenerateProviderResult> {
    const name = intent.prompt.length < 60
      ? intent.prompt.slice(0, 128)
      : 'Custom agent'

    const model = this.getModelForTier(
      intent.modelPreference === 'speed'
        ? 'fast'
        : intent.modelPreference === 'quality'
          ? 'quality'
          : 'balanced'
    )

    const config: UniversalAgentConfig = {
      name,
      description: 'A custom agent generated by Forge (Google mock).',
      instructions: [
        '1. Analyze the user request and determine the objective.',
        '2. Plan the execution steps using available tools and data sources.',
        '3. Execute the plan step by step.',
        '4. If the task is unclear or you lack sufficient information, ask the user for clarification.',
        '5. Summarize the results and present them clearly.'
      ],
      model,
      provider: 'google',
      tools: [{ type: 'google_search' }, { type: 'code_execution' }],
      dataSources: mcps.map((m) => ({
        type: 'api' as const,
        name: m.name,
        url: m.url
      })),
      metadata: { template: slugify(name) }
    }

    return {
      config,
      tokensIn: 120,
      tokensOut: 280
    }
  }

  async lint(config: UniversalAgentConfig): Promise<LintProviderResult> {
    const instructionsText = config.instructions.join('\n')
    const notes: Array<{ severity: 'info' | 'warn' | 'error'; code: string; message: string }> = []

    if (!/\d+\.\s/.test(instructionsText)) {
      notes.push({
        severity: 'error',
        code: 'VAGUE_STEPS',
        message: 'Instructions have no numbered steps.'
      })
    }

    if (config.description.length < 20) {
      notes.push({
        severity: 'warn',
        code: 'MISSING_DESCRIPTION',
        message: 'Agent description is too short.'
      })
    }

    let score = 85
    for (const note of notes) {
      if (note.severity === 'error') score -= 20
      else if (note.severity === 'warn') score -= 10
    }

    return { score: Math.max(0, score), notes }
  }
}
